# Project configuration
name: gke-test-5
domain: gke-test-5.coilysiren.me
zone: coilysiren.me # domain - name = zone
email: coilysiren@gmail.com

# Google Cloud Platform configuration
project: gke-test-5
statebucket: coilysiren-k8s-gpc-tfstate-5
region: us-central1

# https://github.com/cert-manager/cert-manager/releases
cert-manager-version: v1.14.5
