# Project configuration
name: gke-test-5
domain: api.coilysiren.me
zone: coilysiren.me # domain - name = zone
email: coilysiren@gmail.com

# Google Cloud Platform configuration
project: gke-test-5
statebucket: coilysiren-k8s-gpc-tfstate-5
region: us-central1

# AWS Configuration
# AWS doesn't have the same regions as GCP, and also doesn't format then in the same way.
# That said, this isn't a huge issue because we are only using AWS for DNS.
aws-region: us-east-1
aws-profile: coilysiren
