apiVersion: v1
items:
  - apiVersion: networking.k8s.io/v1
    kind: Ingress
    metadata:
      annotations:
        kubernetes.io/ingress.global-static-ip-name: application-ingress
      name: application-ingress
    spec:
      defaultBackend:
        service:
          name: application
          port:
            number: 80
  - apiVersion: v1
    kind: Service
    metadata:
      name: application
    spec:
      ports:
        - port: 80
          protocol: TCP
          targetPort: 8080
      selector:
        app: application
      type: NodePort
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: application
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: application
      template:
        metadata:
          labels:
            app: application
        spec:
          containers:
            - image: us-central1-docker.pkg.dev/gke-test-5/repository/gke-test-5:gkeautopilot-af05c22-kai
              name: application
              ports:
                - containerPort: 8080
              resources:
                requests:
                  cpu: "0.2"
                  memory: 256Mi
kind: List
metadata:
  resourceVersion: ""
