apiVersion: v1
items:
  - apiVersion: v1
    kind: Service
    metadata:
      name: application
    spec:
      ports:
        - port: 80
          targetPort: 8080
          protocol: TCP
      selector:
        app: application
      type: NodePort
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: application
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: application
      template:
        metadata:
          labels:
            app: application
        spec:
          containers:
            - image: us-central1-docker.pkg.dev/gke-test-5/repository/gke-test-5:main-8d0f72c-kai
              name: application
              ports:
                - containerPort: 8080
              resources:
                requests:
                  cpu: "0.1"
                  memory: 256Mi
kind: List
metadata:
  resourceVersion: ""
