apiVersion: v1
items:
  - apiVersion: networking.k8s.io/v1
    kind: Ingress
    metadata:
      annotations:
        cert-manager.io/issuer: letsencrypt-staging
        kubernetes.io/ingress.allow-http: 'true'
        kubernetes.io/ingress.class: gce
      name: application
    spec:
      defaultBackend:
        service:
          name: application
          port:
            number: 8080
      ingressClassName: gce
      tls:
        - hosts:
            - gke-test-2.coilysiren.me
          secretName: tls-secret
  - apiVersion: cert-manager.io/v1
    kind: Issuer
    metadata:
      name: letsencrypt-staging
    spec:
      acme:
        email: coilysiren@gmail.com
        privateKeySecretRef:
          name: letsencrypt-staging
        server: https://acme-staging-v02.api.letsencrypt.org/directory
        solvers:
          - http01:
              ingress:
                name: application
  - apiVersion: v1
    kind: Service
    metadata:
      annotations:
        cloud.google.com/neg: '{"ingress":true}'
      finalizers:
        - service.kubernetes.io/load-balancer-cleanup
      labels:
        app: application
      name: application
    spec:
      allocateLoadBalancerNodePorts: true
      externalTrafficPolicy: Cluster
      internalTrafficPolicy: Cluster
      ports:
        - port: 80
          targetPort: 8080
      selector:
        app: application
      type: LoadBalancer
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      labels:
        app: application
      name: application
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: application
      template:
        metadata:
          labels:
            app: application
        spec:
          containers:
            - image: us-central1-docker.pkg.dev/root-territory-384205/repository/gke-test-2:certs-8ac23d2-kai
              name: application
              ports:
                - containerPort: 8080
kind: List
metadata:
  resourceVersion: ''
