apiVersion: v1
items:
  # https://kubernetes.io/docs/concepts/services-networking/ingress/
  # https://kubernetes.io/docs/reference/kubernetes-api/service-resources/ingress-v1/
  - apiVersion: networking.k8s.io/v1
    kind: Ingress
    metadata:
      annotations:
        kubernetes.io/ingress.allow-http: "true"
        kubernetes.io/ingress.class: gce
      name: application-ingress
    spec:
      defaultBackend:
        service:
          name: application
          port:
            number: 8080
      ingressClassName: gce
      tls:
        - hosts:
            - gke-test-3.coilysiren.me
  # https://kubernetes.io/docs/concepts/services-networking/service/
  # https://kubernetes.io/docs/reference/kubernetes-api/service-resources/service-v1/
  - apiVersion: v1
    kind: Service
    metadata:
      annotations:
        cloud.google.com/neg: '{"ingress":true}'
      finalizers:
        - service.kubernetes.io/load-balancer-cleanup
      labels:
        app: application
      name: application
    spec:
      allocateLoadBalancerNodePorts: true
      externalTrafficPolicy: Cluster
      internalTrafficPolicy: Cluster
      ports:
        - port: 80
          targetPort: 8080
      selector:
        app: application
      type: LoadBalancer
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      labels:
        app: application
      name: application
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: application
      template:
        metadata:
          labels:
            app: application
        spec:
          containers:
            - image: us-central1-docker.pkg.dev/dotted-hope-405813/repository/gke-test-3:certs-c9af36f-kai
              name: application
              ports:
                - containerPort: 8080
kind: List
metadata:
  resourceVersion: ""
