apiVersion: v1
items:
  - apiVersion: v1
    kind: Service
    metadata:
      annotations:
        cloud.google.com/neg: '{"ingress":true}'
      finalizers:
        - service.kubernetes.io/load-balancer-cleanup
      labels:
        app: application
      name: application
    spec:
      allocateLoadBalancerNodePorts: true
      externalTrafficPolicy: Cluster
      internalTrafficPolicy: Cluster
      ports:
        - name: http
          port: 80
          targetPort: 8080
        - name: https
          port: 443
          targetPort: 8080
        - name: application
          port: 8080
          targetPort: 8080
      selector:
        app: application
      type: LoadBalancer
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      labels:
        app: application
      name: application
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: application
      template:
        metadata:
          labels:
            app: application
        spec:
          containers:
            - image: us-central1-docker.pkg.dev/dotted-hope-405813/repository/gke-test-3:certs-66b6b77-kai
              name: application
              ports:
                - containerPort: 8080
kind: List
metadata:
  resourceVersion: ''
